import {defineField, defineType} from 'sanity'

export const homepageType = defineType({
  name: 'homepage',
  title: 'Sākumlapa',
  type: 'document',
  groups: [
    {name: 'hero', title: 'Ievads', default: true},
    {name: 'highlights', title: 'Akcenti'},
    {name: 'editorial', title: 'Redakcionālā galerija'},
    {name: 'contact', title: 'Kontaktu sadaļa'},
    {name: 'seo', title: 'SEO'},
  ],
  fields: [
    defineField({
      name: 'title',
      title: 'Iekšējais nosaukums',
      type: 'string',
      group: 'hero',
      initialValue: 'Sākumlapa',
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: 'heroEyebrow',
      title: 'Ievada virsraksta rinda',
      type: 'string',
      group: 'hero',
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: 'heroTitle',
      title: 'Ievada virsraksts',
      type: 'string',
      group: 'hero',
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: 'heroLead',
      title: 'Ievada apraksts',
      type: 'text',
      rows: 4,
      group: 'hero',
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: 'heroBackgroundImage',
      title: 'Ievada fona attēls',
      type: 'image',
      group: 'hero',
      options: {hotspot: true},
    }),
    defineField({
      name: 'availabilityTitle',
      title: 'Pieejamības virsraksts',
      type: 'string',
      group: 'hero',
    }),
    defineField({
      name: 'metrics',
      title: 'Rādītāji',
      type: 'array',
      group: 'hero',
      of: [{type: 'metricItem'}],
    }),
    defineField({
      name: 'projectHighlightsEyebrow',
      title: 'Akcentu virsraksta rinda',
      type: 'string',
      group: 'highlights',
    }),
    defineField({
      name: 'projectHighlightsTitle',
      title: 'Akcentu virsraksts',
      type: 'string',
      group: 'highlights',
    }),
    defineField({
      name: 'projectHighlightsGalleryAriaLabel',
      title: 'Akcentu galerijas ARIA etiķete',
      type: 'string',
      group: 'highlights',
    }),
    defineField({
      name: 'projectFeatures',
      title: 'Projekta priekšrocības',
      type: 'array',
      group: 'highlights',
      of: [{type: 'featureItem'}],
    }),
    defineField({
      name: 'projectGallery',
      title: 'Projekta galerija',
      type: 'array',
      group: 'highlights',
      of: [{type: 'galleryImage'}],
    }),
    defineField({
      name: 'editorialEyebrow',
      title: 'Redakcionālās sadaļas virsraksta rinda',
      type: 'string',
      group: 'editorial',
    }),
    defineField({
      name: 'editorialTitle',
      title: 'Redakcionālās sadaļas virsraksts',
      type: 'string',
      group: 'editorial',
    }),
    defineField({
      name: 'editorialLead',
      title: 'Redakcionālās sadaļas apraksts',
      type: 'text',
      rows: 4,
      group: 'editorial',
    }),
    defineField({
      name: 'editorialRowAriaLabel',
      title: 'Redakcionālās rindas ARIA etiķete',
      type: 'string',
      group: 'editorial',
    }),
    defineField({
      name: 'editorialImages',
      title: 'Redakcionālie attēli',
      type: 'array',
      group: 'editorial',
      of: [{type: 'galleryImage'}],
    }),
    defineField({
      name: 'contactEyebrow',
      title: 'Kontaktu virsraksta rinda',
      type: 'string',
      group: 'contact',
    }),
    defineField({
      name: 'contactTitle',
      title: 'Kontaktu virsraksts',
      type: 'string',
      group: 'contact',
    }),
    defineField({
      name: 'contactLead',
      title: 'Kontaktu apraksts',
      type: 'text',
      rows: 4,
      group: 'contact',
    }),
    defineField({
      name: 'contactBenefits',
      title: 'Kontaktu ieguvumi',
      type: 'array',
      group: 'contact',
      of: [{type: 'string'}],
    }),
    defineField({
      name: 'seo',
      title: 'SEO',
      type: 'seo',
      group: 'seo',
    }),
  ],
  preview: {
    select: {
      title: 'title',
      media: 'heroBackgroundImage',
    },
  },
})
