import {defineField, defineType} from 'sanity'

export const howToBuyPageType = defineType({
  name: 'howToBuyPage',
  title: 'Kā iegādāties lapa',
  type: 'document',
  groups: [
    {name: 'hero', title: 'Ievads', default: true},
    {name: 'steps', title: 'Soļi'},
    {name: 'financing', title: 'Finansējums'},
    {name: 'documents', title: 'Dokumenti'},
    {name: 'faq', title: 'Biežākie jautājumi'},
    {name: 'contact', title: 'Kontakti'},
  ],
  fields: [
    defineField({
      name: 'title',
      title: 'Iekšējais nosaukums',
      type: 'string',
      group: 'hero',
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: 'heroEyebrow',
      title: 'Ievada virsraksta rinda',
      type: 'string',
      group: 'hero',
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: 'heroTitle',
      title: 'Ievada virsraksts',
      type: 'string',
      group: 'hero',
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: 'heroLead',
      title: 'Ievada apraksts',
      type: 'text',
      rows: 4,
      group: 'hero',
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: 'heroImage',
      title: 'Ievada attēls',
      type: 'image',
      group: 'hero',
      options: {hotspot: true},
      description: 'Ieteicams plats arhitektūras attēls lapas ievadam.',
    }),
    defineField({
      name: 'stepsEyebrow',
      title: 'Soļu virsraksta rinda',
      type: 'string',
      group: 'steps',
    }),
    defineField({
      name: 'stepsTitle',
      title: 'Soļu virsraksts',
      type: 'string',
      group: 'steps',
    }),
    defineField({
      name: 'stepsLead',
      title: 'Soļu apraksts',
      type: 'text',
      rows: 4,
      group: 'steps',
    }),
    defineField({
      name: 'steps',
      title: 'Soļi',
      type: 'array',
      group: 'steps',
      of: [{type: 'howToBuyStep'}],
      validation: (rule) => rule.min(3),
    }),
    defineField({
      name: 'financingEyebrow',
      title: 'Finansējuma virsraksta rinda',
      type: 'string',
      group: 'financing',
    }),
    defineField({
      name: 'financingTitle',
      title: 'Finansējuma virsraksts',
      type: 'string',
      group: 'financing',
    }),
    defineField({
      name: 'financingLead',
      title: 'Finansējuma apraksts',
      type: 'text',
      rows: 4,
      group: 'financing',
    }),
    defineField({
      name: 'financingImage',
      title: 'Finansējuma attēls',
      type: 'galleryImage',
      group: 'financing',
      description: 'Papildu attēls finansējuma sadaļai (nav obligāts).',
    }),
    defineField({
      name: 'financingHighlights',
      title: 'Finansējuma punkti',
      type: 'array',
      group: 'financing',
      of: [{type: 'detailItem'}],
    }),
    defineField({
      name: 'documentsEyebrow',
      title: 'Dokumentu virsraksta rinda',
      type: 'string',
      group: 'documents',
    }),
    defineField({
      name: 'documentsTitle',
      title: 'Dokumentu virsraksts',
      type: 'string',
      group: 'documents',
    }),
    defineField({
      name: 'documentsLead',
      title: 'Dokumentu apraksts',
      type: 'text',
      rows: 4,
      group: 'documents',
    }),
    defineField({
      name: 'documentsImage',
      title: 'Dokumentu attēls',
      type: 'galleryImage',
      group: 'documents',
      description: 'Papildu attēls dokumentu sadaļai (nav obligāts).',
    }),
    defineField({
      name: 'documentItems',
      title: 'Dokumentu saraksts',
      type: 'array',
      group: 'documents',
      of: [{type: 'detailItem'}],
    }),
    defineField({
      name: 'faqEyebrow',
      title: 'Biežāko jautājumu virsraksta rinda',
      type: 'string',
      group: 'faq',
    }),
    defineField({
      name: 'faqTitle',
      title: 'Biežāko jautājumu virsraksts',
      type: 'string',
      group: 'faq',
    }),
    defineField({
      name: 'faqLead',
      title: 'Biežāko jautājumu apraksts',
      type: 'text',
      rows: 4,
      group: 'faq',
    }),
    defineField({
      name: 'faqItems',
      title: 'Biežāko jautājumu ieraksti',
      type: 'array',
      group: 'faq',
      of: [{type: 'howToBuyFaqItem'}],
    }),
    defineField({
      name: 'contactEyebrow',
      title: 'Kontaktu virsraksta rinda',
      type: 'string',
      group: 'contact',
    }),
    defineField({
      name: 'contactTitle',
      title: 'Kontaktu virsraksts',
      type: 'string',
      group: 'contact',
    }),
    defineField({
      name: 'contactLead',
      title: 'Kontaktu apraksts',
      type: 'text',
      rows: 4,
      group: 'contact',
    }),
    defineField({
      name: 'contactBenefits',
      title: 'Kontaktu ieguvumi',
      type: 'array',
      group: 'contact',
      of: [{type: 'string'}],
    }),
    defineField({
      name: 'contactFormTitle',
      title: 'Kontaktu formas virsraksts',
      type: 'string',
      group: 'contact',
    }),
    defineField({
      name: 'contactFormIntro',
      title: 'Kontaktu formas ievadteksts',
      type: 'text',
      rows: 3,
      group: 'contact',
    }),
    defineField({
      name: 'contactDefaultInformation',
      title: 'Noklusējuma informācijas teksts',
      type: 'text',
      rows: 3,
      group: 'contact',
      description: 'Aizpilda kontaktformas informācijas lauku šajā lapā.',
    }),
    defineField({
      name: 'contactSubmitLabel',
      title: 'Iesniegšanas pogas teksts',
      type: 'string',
      group: 'contact',
    }),
  ],
  preview: {
    select: {
      title: 'title',
      subtitle: 'heroTitle',
      media: 'heroImage',
    },
  },
})
