import {defineField, defineType} from 'sanity'

export const propertyDocument = defineType({
  name: 'property',
  title: 'Īpašums',
  type: 'document',
  groups: [
    {name: 'content', title: 'Saturs', default: true},
    {name: 'media', title: 'Attēli'},
    {name: 'details', title: 'Parametri'},
    {name: 'seo', title: 'SEO'},
  ],
  fields: [
    defineField({
      name: 'title',
      title: 'Nosaukums',
      type: 'string',
      group: 'content',
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: 'slug',
      title: 'Saīsne (slug)',
      type: 'slug',
      group: 'content',
      options: {source: 'title', maxLength: 96},
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: 'propertyCode',
      title: 'Īpašuma kods',
      type: 'string',
      group: 'content',
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: 'propertyType',
      title: 'Īpašuma tips',
      type: 'reference',
      to: [{type: 'propertyType'}],
      description: 'Nosaka, zem kura kataloga filtra šis īpašums būs redzams.',
      group: 'content',
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: 'project',
      title: 'Projekts',
      type: 'reference',
      to: [{type: 'project'}],
      description: 'Piesaisti īpašumu projektam (vienam projektam var būt vairāki īpašumi).',
      group: 'content',
    }),
    defineField({
      name: 'status',
      title: 'Statuss',
      type: 'string',
      group: 'content',
      options: {
        list: [
          {title: 'Pieejams', value: 'available'},
          {title: 'Rezervēts', value: 'reserved'},
          {title: 'Pārdots', value: 'sold'},
        ],
        layout: 'radio',
      },
      initialValue: 'available',
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: 'shortDescription',
      title: 'Īss apraksts',
      type: 'text',
      rows: 3,
      group: 'content',
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: 'heroImage',
      title: 'Galvenais attēls',
      type: 'image',
      group: 'media',
      options: {hotspot: true},
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: 'gallery',
      title: 'Galerija',
      type: 'array',
      group: 'media',
      of: [{type: 'galleryImage'}],
      validation: (rule) => rule.min(1),
    }),
    defineField({
      name: 'floorPlanImage',
      title: 'Plānojuma attēls',
      type: 'image',
      group: 'media',
      options: {hotspot: true},
    }),
    defineField({
      name: 'floorPlanSectionTitle',
      title: 'Plānojuma sadaļas virsraksts',
      type: 'string',
      description: 'Galvenais virsraksts virs plānojuma sadaļas, piemēram: "4 istabu dzīvokļa plāns".',
      group: 'content',
    }),
    defineField({
      name: 'floorPlanCardTitle',
      title: 'Plānojuma kartītes virsraksts',
      type: 'string',
      description: 'Virsraksts blakus plānojuma attēlam, piemēram: "4 istabu plāns".',
      group: 'content',
    }),
    defineField({
      name: 'floorPlanNote',
      title: 'Plānojuma piezīme',
      type: 'text',
      rows: 3,
      group: 'content',
    }),
    defineField({
      name: 'aboutSectionTitle',
      title: 'Sadaļas “Par dzīvokli” virsraksts',
      type: 'string',
      description: 'Galvenais virsraksts sadaļā “Par dzīvokli”.',
      group: 'content',
    }),
    defineField({
      name: 'description',
      title: 'Apraksts',
      type: 'array',
      group: 'content',
      of: [{type: 'block'}],
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: 'rooms',
      title: 'Istabas',
      type: 'number',
      group: 'details',
      validation: (rule) => rule.required().min(1),
    }),
    defineField({
      name: 'area',
      title: 'Platība (m²)',
      type: 'number',
      group: 'details',
      validation: (rule) => rule.required().positive(),
    }),
    defineField({
      name: 'price',
      title: 'Cena',
      type: 'number',
      group: 'details',
      validation: (rule) => rule.required().min(0),
    }),
    defineField({
      name: 'currency',
      title: 'Valūta',
      type: 'string',
      group: 'details',
      initialValue: 'EUR',
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: 'floor',
      title: 'Stāvs',
      type: 'number',
      group: 'details',
      validation: (rule) => rule.required().min(0),
    }),
    defineField({
      name: 'building',
      title: 'Korpuss',
      type: 'string',
      group: 'details',
    }),
    defineField({
      name: 'details',
      title: 'Parametru rindas',
      type: 'array',
      group: 'details',
      of: [{type: 'detailItem'}],
    }),
    defineField({
      name: 'seo',
      title: 'SEO',
      type: 'seo',
      group: 'seo',
    }),
  ],
  orderings: [
    {
      title: 'Cena: no zemākās uz augstāko',
      name: 'priceAsc',
      by: [{field: 'price', direction: 'asc'}],
    },
    {
      title: 'Cena: no augstākās uz zemāko',
      name: 'priceDesc',
      by: [{field: 'price', direction: 'desc'}],
    },
  ],
  preview: {
    select: {
      title: 'title',
      code: 'propertyCode',
      status: 'status',
      media: 'heroImage',
    },
    prepare({title, code, status, media}) {
      const statusLabel = status ? String(status).toUpperCase() : 'MELNRAKSTS'
      return {
        title,
        subtitle: code ? `${code} • ${statusLabel}` : statusLabel,
        media,
      }
    },
  },
})
